apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-service-config
  namespace: fintech
data:
  PORT: "3002"
  API_GATEWAY_URL: "http://api-gateway.fintech.svc.cluster.local"
  PUBLIC_API_GATEWAY_URL: "http://127.0.0.1"
