apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: fintech
data:
  REDIS_CLUSTER_NODES: "redis-cluster-0.redis-cluster.data.svc.cluster.local:6379,redis-cluster-1.redis-cluster.data.svc.cluster.local:6379,redis-cluster-2.redis-cluster.data.svc.cluster.local:6379"
  KAFKA_BOOTSTRAP: "fintech-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
