apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: fintech
data:
  REDIS_CLUSTER_ADDRS: "redis-cluster-0.redis-cluster.data.svc.cluster.local:6379,redis-cluster-1.redis-cluster.data.svc.cluster.local:6379,redis-cluster-2.redis-cluster.data.svc.cluster.local:6379"
  PORT: "8080"
