apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: fintech
type: Opaque
stringData:
  DATABASE_URL: "postgres://authuser:authpass123@auth-postgres:5432/authdb"
  JWT_SECRET: "dev-jwt-secret-change-in-prod"
