apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-service-config
  namespace: fintech
data:
  KAFKA_BOOTSTRAP: "fintech-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  DYNAMODB_ENDPOINT: "http://dynamodb-local.data.svc.cluster.local:8000"
